#!/bin/bash
###############################################################################
# EC2 user-data: bootstrap a Docker Compose runtime for the Java app.
#
# Steps:
#   1. Install Docker Engine, Compose v2 plugin, AWS CLI v2, jq, CW Agent.
#   2. Pull image tags + DB endpoint from SSM and secrets from Secrets Manager.
#   3. Authenticate to ECR.
#   4. Render /opt/java-app/.env, fetch docker-compose.prod.yml from SSM-pointed
#      S3 URI, then `docker compose up -d`.
#   5. Configure CloudWatch Agent.
###############################################################################
set -euo pipefail

REGION="${aws_region}"
LOG_GROUP="${log_group_name}"

# ---- log everything to /var/log/user-data.log too ----
exec > >(tee -a /var/log/user-data.log /var/log/cloud-init-output.log) 2>&1

echo "[user-data] starting at $(date -Iseconds)"

# ---- base packages ----
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y ca-certificates curl gnupg lsb-release jq unzip awscli

# ---- Docker Engine + Compose plugin (official Docker apt repo) ----
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
. /etc/os-release
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $${VERSION_CODENAME} stable" | tee /etc/apt/sources.list.d/docker.list >/dev/null
apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

systemctl enable --now docker

# ---- AWS CLI v2 (apt awscli is v1; replace with v2) ----
curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
unzip -q /tmp/awscliv2.zip -d /tmp
/tmp/aws/install --update
rm -rf /tmp/aws /tmp/awscliv2.zip

# ---- CloudWatch Agent ----
curl -fsSL "https://s3.${aws_region}.amazonaws.com/amazoncloudwatch-agent-${aws_region}/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb" -o /tmp/cwa.deb
dpkg -i -E /tmp/cwa.deb || apt-get install -fy
rm -f /tmp/cwa.deb

# ---- App directory ----
mkdir -p /opt/java-app
cd /opt/java-app

# ---- Pull release metadata + DB endpoint from SSM ----
BACKEND_TAG=$(aws ssm get-parameter --region "$REGION" --name "${ssm_backend_tag}"  --query 'Parameter.Value' --output text)
FRONTEND_TAG=$(aws ssm get-parameter --region "$REGION" --name "${ssm_frontend_tag}" --query 'Parameter.Value' --output text)
RELEASE_ID=$(aws ssm get-parameter --region "$REGION" --name "${ssm_release_id}"   --query 'Parameter.Value' --output text)
DB_HOST=$(aws ssm get-parameter --region "$REGION" --name "${ssm_db_endpoint}"     --query 'Parameter.Value' --output text)
DB_NAME=$(aws ssm get-parameter --region "$REGION" --name "${ssm_db_name}"         --query 'Parameter.Value' --output text)
COMPOSE_OBJ=$(aws ssm get-parameter --region "$REGION" --name "${ssm_compose_object}" --query 'Parameter.Value' --output text)

# ---- Pull DB app-user creds from Secrets Manager ----
DB_USER_JSON=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "${secret_db_app_user}" --query 'SecretString' --output text)
DB_USER=$(echo "$DB_USER_JSON" | jq -r .username)
DB_PASS=$(echo "$DB_USER_JSON" | jq -r .password)

# JWT (only used by backend at runtime - pulled by the backend itself via
# Secrets Manager too; here we only export the secret name as an env var).
JWT_SECRET_NAME="${secret_jwt}"
SES_SECRET_NAME="${secret_ses}"
ADMIN_SECRET_NAME="${secret_admin}"

# ---- Render .env file (mode 0600, root-owned) ----
umask 077
cat >/opt/java-app/.env <<EOF
# Generated by user-data on $(date -Iseconds)
RELEASE_ID=$${RELEASE_ID}
BACKEND_IMAGE=${backend_repo_url}:$${BACKEND_TAG}
FRONTEND_IMAGE=${frontend_repo_url}:$${FRONTEND_TAG}

AWS_REGION=$${REGION}

DB_HOST=$${DB_HOST}
DB_PORT=3306
DB_NAME=$${DB_NAME}
DB_USERNAME=$${DB_USER}
DB_PASSWORD=$${DB_PASS}

JWT_SECRET_NAME=$${JWT_SECRET_NAME}
SES_SECRET_NAME=$${SES_SECRET_NAME}
ADMIN_SECRET_NAME=$${ADMIN_SECRET_NAME}

APP_PUBLIC_URL=https://${app_subdomain}:8443
EOF
chmod 0600 /opt/java-app/.env

# ---- Fetch docker-compose.prod.yml from S3 (pointer in SSM) ----
if [[ "$${COMPOSE_OBJ}" == s3://* ]]; then
  aws s3 cp "$${COMPOSE_OBJ}" /opt/java-app/docker-compose.yml
else
  echo "[user-data] WARNING: compose-object SSM value is '$${COMPOSE_OBJ}' (not s3:// URI)."
  # Sane default to keep the box up if compose isn't published yet.
  cat >/opt/java-app/docker-compose.yml <<'YAML'
services:
  placeholder:
    image: nginx:1.27-alpine
    ports: ["8080:80"]
    restart: unless-stopped
YAML
fi

# ---- ECR auth ----
aws ecr get-login-password --region "$REGION" | \
  docker login --username AWS --password-stdin "${deployment_account}.dkr.ecr.$REGION.amazonaws.com"

# ---- Compose up ----
cd /opt/java-app
docker compose --env-file /opt/java-app/.env pull || true
docker compose --env-file /opt/java-app/.env up -d --remove-orphans

# ---- CloudWatch Agent config ----
cat >/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<JSON
{
  "agent": { "metrics_collection_interval": 60, "run_as_user": "root" },
  "metrics": {
    "namespace": "JavaApp/EC2",
    "append_dimensions": {
      "InstanceId": "\$${aws:InstanceId}",
      "AutoScalingGroupName": "\$${aws:AutoScalingGroupName}"
    },
    "metrics_collected": {
      "cpu":  { "measurement": ["cpu_usage_idle","cpu_usage_iowait","cpu_usage_user","cpu_usage_system"], "totalcpu": true },
      "mem":  { "measurement": ["mem_used_percent"] },
      "disk": { "measurement": ["used_percent"], "resources": ["/"] },
      "diskio": { "measurement": ["io_time"] }
    }
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          { "file_path": "/var/log/user-data.log",       "log_group_name": "$${LOG_GROUP}", "log_stream_name": "{instance_id}/user-data" },
          { "file_path": "/var/log/cloud-init-output.log","log_group_name": "$${LOG_GROUP}", "log_stream_name": "{instance_id}/cloud-init" },
          { "file_path": "/var/lib/docker/containers/*/*-json.log", "log_group_name": "$${LOG_GROUP}", "log_stream_name": "{instance_id}/docker" }
        ]
      }
    }
  }
}
JSON

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
  -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

echo "[user-data] done at $(date -Iseconds)"
